In [16]:
import seaborn as sns
import pickle
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import classification_report

PATH = "path"
MODEL = "model"
FOLD = 4
EPOCH = 100


In [17]:
def acc(matrix,dataset_size):
        taikaku1 = sum(np.diag(matrix)) #対角成分
        taikaku2 = sum(np.diag(matrix, k=1)) + sum(np.diag(matrix, k=-1)) #対角成分の両サイド
        other1 = dataset_size-taikaku1 #normal
        other2 = dataset_size-taikaku1-taikaku2 #1-neighbor
        
        print(f'taikaku1:{taikaku1}, taikaku2:{taikaku2}, taikaku_total:{taikaku1+taikaku2}')
        print(f'dataset_size:{dataset_size}, other1:{other1}, other2:{other2}')
        return taikaku1/dataset_size,(taikaku1+taikaku2)/dataset_size,taikaku1,taikaku1+taikaku2

matrix = np.loadtxt(PATH, dtype=int)
print(matrix)

normal_acc, neighbor_acc, taikaku1,taikaku2 = acc(matrix,np.sum(matrix))
print()

print(f'normal_acc:{normal_acc}, neighbor_acc:{neighbor_acc}')
print(f'taikaku1:{taikaku1}, taikaku2:{taikaku2}')

[[32  5  1  0  0  0  0]
 [12  5  1  0  0  0  0]
 [ 1  4  4  5  0  0  0]
 [ 0  2  1 32  0  1  0]
 [ 0  0  0  1  3  1  0]
 [ 0  0  0  1  1  2  0]
 [ 0  0  0  0  0  1  2]]
taikaku1:80, taikaku2:32, taikaku_total:112
dataset_size:118, other1:38, other2:6

normal_acc:0.6779661016949152, neighbor_acc:0.9491525423728814
taikaku1:80, taikaku2:112


In [ ]:
sns.set(font_scale = 2.5)
cm = pd.DataFrame(data=matrix, 
                  index=[], 
                  columns=[])

plt.figure(figsize=(15, 15))

sns.heatmap(cm,
            square=True, 
            cbar=True,
            annot=True, 
            cmap='Blues',
            fmt='d',
            vmax=40,
            vmin=0,
            center=19,
            annot_kws={"size":20})

plt.title(f'{MODEL}   {FOLD}Fold  {EPOCH}Epoch\nNormal-Acc: {normal_acc:.4f}'
          f'({taikaku1}/{np.sum(matrix)})\n1Neighbor-Acc: {neighbor_acc:.4f}  ({taikaku2}/{np.sum(matrix)})')
plt.yticks(rotation=0)
plt.xticks(rotation=45)
plt.xlabel("Predicted Label", fontsize=30, rotation=0)
plt.ylabel("True Label", fontsize=30)
plt.subplots_adjust(left=0.1, right=0.95, bottom=0.1, top=0.95)